### ISSUE TITLE
How do "Until" and "ANDSTL" work?

### ISSUE THREAD

**Issue by xiayu3333** [balsini/SignalTemplateLibraryAutogen#1]
Hello,

I am currently trying to use your STLLib.slx to build my model.
However, I have difficulties figuring out how to use "**Until**" and "**ANDSTL**".  Please see the picture below.

For "Until", I guess **FIRST** is the first proposition, **SECOND** is the second proposition. Are **EN** and **EOI** the STL bounded operator?  
For "ANDSTL", it seems that **VALID** equals to **Q**. What is **DELAY** stands for and used for?

It would be very helpful if you could help me with this, or tell me where I can find the explanations/descriptions. Thanks.

A user

![Screenshot from 2021-06-08 13-35-12](https://user-images.githubusercontent.com/55579160/121178093-69a78780-c85e-11eb-8855-cb56309134a1.png)

**Comment by xiayu3333** [comment]
I have figured out what DELAY in "ANDSTL" is used for: it turns the temporal bound [a, b] to [t + a, t + b].
Isn't it?

**Comment by xiayu3333** [comment]
I think I get what DELAY in ANDSTL is used for: 
         it turns the temporal bound [a, b] into [t+a, t+b].
Am I right?

**Comment by balsini** [comment]
Oh, wow, this was a long time ago... :) I'm a bit rusty on this library and I don't have Matlab to explore the model, hopefully the paper [Generation of Simulink Monitors for Control Applications from Formal Requirements](http://retis.sssup.it/~marco/papers/2017/sies.pdf) would give the formal definition of what these modules implement.

I guess EN and EOI in Until are used for time-constrained Until (instead of being in [0, +inf)), while the delay in ANDSTL is used to ensure in a closed loop that the AND condition is valid for all the set of inputs.

**Comment by xiayu3333** [comment]
In fact, I saw this paper first and get to see this repository thanks to it. By the way, thanks a lot, this paper is really inspiring to me, because I am doing something similar to what you have done.

I have difficulties getting the formal definitions because what you wrote in the paper sometimes does not match what's in the repository. For example, the following is in the paper, and the blocks look slightly different from the ones that I see in the repo (see picture above in my first comment). 

![Screenshot from 2021-06-10 09-29-18](https://user-images.githubusercontent.com/55579160/121483792-dfcafc00-c9ce-11eb-9429-857e6112f72e.png)

I suppose you have done some improvement after releasing this paper. Anyways, it's no big deal. I will try to figure it out myself and share my findings with you, if you are still interested.

PS, in the paper I see this "**Library for the generation of Control monitor**"  (see the picture down below), but I cannot find it anywhere in the repo. Could you please help?

![2](https://user-images.githubusercontent.com/55579160/121484522-97600e00-c9cf-11eb-8b05-489df97cf4d7.png)
